version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PHP_MEM_LIMIT=256
      - SKIP_CHOWN=true
    env_file:
      - .env
    ports:
      - '8088:80'
    volumes:
      - ./:/var/www/html
    container_name: app_contacts

  db-pgsql:
    image: postgres:14.7-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=senhaSuPErSeCREt@
      - POSTGRES_USER=postgres
      - POSTGRES_DB=people_contacts
      - TZ='America/Sao_Paulo'
    volumes:
      - ./db:/var/lib/postgresql/data/